name: moviedb
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.3.5
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - secrets.json
